model_params:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 0
  norm_weight: True
  beta: 0.0
mf:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 0
  norm_weight: True
  beta: 0.0
rmf:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 0
  norm_weight: True
  beta: 0.0
oracle:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 0
  norm_weight: True
  beta: 0.0
bpr:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 0
  norm_weight: True
  beta: 0.0
ubpr:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 0
  norm_weight: True
  beta: 0.0
ubpr_nclip:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 0
  norm_weight: True
  beta: 100000000.0
ipwbpr:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 0
  norm_weight: False
  beta: 0.0
ipwbpr_opt0:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 1
  norm_weight: False
  beta: 0.0
ipwbpr_opt1:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 1
  norm_weight: True
  beta: 0.0
ipwbpr_opt2:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 2
  norm_weight: False
  beta: 0.0
ipwbpr_opt3:
  dim: 10
  lam: 0.00001
  eta: 0.1
  max_iters: 1000
  batch_size: 12
  pair_weight: 2
  norm_weight: True
  beta: 0.0
generate_sys_params:
  iters: 300
  batch_size: 256
  dim: 20
  eta: 0.01

